#!/usr/bin/env python3
import json

with open('data/cities/okinawa.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

# Keep original 25 spots
existing = existing[:25]

new_spots = [
  {
    "id": "oki_p_26",
    "name": "浜辺の茶屋",
    "name_ja": "浜辺の茶屋",
    "name_en": "Hamabe no Chaya",
    "category": "Café & Dining",
    "rating": "★4.6",
    "desc": "南城市玉城の海岸に佇む元祖海カフェ。窓枠がそのまま額縁のように目の前の遠浅の海と空を切り取る絶景スポット。",
    "desc_ja": "南城市玉城の海岸に佇む元祖海カフェ。窓枠がそのまま額縁のように目の前の遠浅の海と空を切り取る絶景スポット。",
    "desc_en": "An iconic seaside cafe perched on the edge of Tamagusuku beach, famous for unobstructed tidal views framing the ocean like a living painting.",
    "price": "ドリンク・スイーツ：約600円〜",
    "price_ja": "ドリンク・スイーツ：約600円〜",
    "price_en": "Drinks & Sweets ~¥600+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1328,
    "lng": 127.7816,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": True,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 満潮時は足元まで海水が迫り海に浮かんでいる感覚、干潮時は沖合まで潮が引いて砂浜散策が楽しめます。窓際カウンター席はオープン直後（10:00）の到着が狙い目です。",
    "tip_ja": "💡 満潮時は足元まで海水が迫り海に浮かんでいる感覚、干潮時は沖合まで潮が引いて砂浜散策が楽しめます。窓際カウンター席はオープン直後（10:00）の到着が狙い目です。",
    "tip_en": "Visit at high tide to feel suspended above turquoise waters, or low tide to stroll across exposed reef sands. Arrive right at 10 AM for the coveted window seats.",
    "categories": ["Café", "Scenery"]
  },
  {
    "id": "oki_p_27",
    "name": "カフェくるくま",
    "name_ja": "カフェくるくま",
    "name_en": "Cafe Curcuma",
    "category": "Café & Dining",
    "rating": "★4.6",
    "desc": "太平洋を見渡す高台の断崖絶壁に広がる絶景アジアンカフェ。本格タイ料理やハーブティーを大パノラマとともに味わえる名店。",
    "desc_ja": "太平洋を見渡す高台の断崖絶壁に広がる絶景アジアンカフェ。本格タイ料理やハーブティーを大パノラマとともに味わえる名店。",
    "desc_en": "A cliff-top panoramic Asian herb cafe in Nanjo overlooking the Pacific Ocean, famous for authentic Thai curries and sweeping open-terrace ocean views.",
    "price": "ランチ：約1,400円〜",
    "price_ja": "ランチ：約1,400円〜",
    "price_en": "Lunch ~¥1,400+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1669,
    "lng": 127.8176,
    "rain": False,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 3種のカレー（チキン・ポーク・ビーフ）が一度に味わえる「くるくまスペシャル」が一番人気。テラス席での写真撮影は食前・食後に自由に入退場可能です。",
    "tip_ja": "💡 3種のカレー（チキン・ポーク・ビーフ）が一度に味わえる「くるくまスペシャル」が一番人気。テラス席での写真撮影は食前・食後に自由に入退場可能です。",
    "tip_en": "Order the Curcuma Special featuring three distinct curry styles. Visitors are welcome to explore the open wooden lookout deck for photography before or after dining.",
    "categories": ["Café", "Scenery"]
  },
  {
    "id": "oki_p_28",
    "name": "ピザ喫茶 花人逢",
    "name_ja": "ピザ喫茶 花人逢",
    "name_en": "Kajinhou Pizza in the Sky",
    "category": "Café & Dining",
    "rating": "★4.7",
    "desc": "本部町の小高い山の上に佇む古民家ピザカフェ。縁側から東シナ海と伊江島タッチューを望みながら手作りピザが味わえる。",
    "desc_ja": "本部町の小高い山の上に佇む古民家ピザカフェ。縁側から東シナ海と伊江島タッチューを望みながら手作りピザが味わえる。",
    "desc_en": "A mountaintop traditional Ryukyuan house pizzeria in Motobu, offering fresh oven-baked pizzas and panoramic vistas of Ie Island across the East China Sea.",
    "price": "ピザ（中）：約1,500円 / サラダ：約700円",
    "price_ja": "ピザ（中）：約1,500円 / サラダ：約700円",
    "price_en": "Pizza ~¥1,500",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.6669,
    "lng": 127.9048,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 メニューはピザとサラダのみとシンプルですが、大宜味村の湧水で仕込んだ生地が絶品。美ら海水族館から車で15分なのでランチルートに最適です。",
    "tip_ja": "💡 メニューはピザとサラダのみとシンプルですが、大宜味村の湧水で仕込んだ生地が絶品。美ら海水族館から車で15分なのでランチルートに最適です。",
    "tip_en": "The focused menu centers on hand-tossed cheese pizza made with natural spring water. Located just a 15-minute drive from Churaumi Aquarium.",
    "categories": ["Café"]
  },
  {
    "id": "oki_p_29",
    "name": "Transit Cafe",
    "name_ja": "Transit Cafe",
    "name_en": "Transit Cafe Chatan",
    "category": "Café & Dining",
    "rating": "★4.5",
    "desc": "北谷町宮城海岸沿いにあるオーシャンフロントリゾートカフェ。白を基調としたテラス席から夕日と東シナ海の水平線を一望できる。",
    "desc_ja": "北谷町宮城海岸沿いにあるオーシャンフロントリゾートカフェ。白を基調としたテラス席から夕日と東シナ海の水平線を一望できる。",
    "desc_en": "A sleek seaside balcony restaurant in Chatan overlooking Miyagi Coast, celebrated for sunset cocktails, seafood pastas, and coastal dining.",
    "price": "ランチ：約1,500円〜 / ディナー：約3,000円〜",
    "price_ja": "ランチ：約1,500円〜 / ディナー：約3,000円〜",
    "price_en": "Lunch ~¥1,500+ / Dinner ~¥3,000+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.3312,
    "lng": 127.7478,
    "rain": False,
    "kids": False,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": True,
    "tip": "💡 夕暮れ時のテラス席は事前予約が推奨されます。名物の「カマンベールチーズフォンデュ」やトロピカルカクテルが女性やカップルに大人気です。",
    "tip_ja": "💡 夕暮れ時のテラス席は事前予約が推奨されます。名物の「カマンベールチーズフォンデュ」やトロピカルカクテルが女性やカップルに大人気です。",
    "tip_en": "Reserve a terrace seat for sunset viewing over Miyagi coast. The warm baked Camembert fondue with baguette pairs wonderfully with tropical mocktails.",
    "categories": ["Café", "Night"]
  },
  {
    "id": "oki_p_30",
    "name": "きしもと食堂 本店",
    "name_ja": "きしもと食堂 本店",
    "name_en": "Kishimoto Shokudo (Main Branch)",
    "category": "Café & Dining",
    "rating": "★4.6",
    "desc": "明治38年（1905年）創業の沖縄そばの老舗。ガジュマルの木灰を使った伝統の木灰そばと豚骨カツオ出汁を守り続ける伝説の名店。",
    "desc_ja": "明治38年（1905年）創業の沖縄そばの老舗。ガジュマルの木灰を使った伝統の木灰そばと豚骨カツオ出汁を守り続ける伝説の名店。",
    "desc_en": "Established in 1905 in Motobu, this legendary eatery serves traditional wood-ash Okinawa soba topped with tender braised pork belly and rich bonito-pork broth.",
    "price": "そば（大）：約850円 / ジューシー：約300円",
    "price_ja": "そば（大）：約850円 / ジューシー：約300円",
    "price_en": "Soba ~¥850",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.6575,
    "lng": 127.8887,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 数量限定の沖縄風炊き込みご飯「ジューシー」は昼過ぎには売り切れることが多いため、午前中（11:00開店直後）の訪問が安心です。",
    "tip_ja": "💡 数量限定の沖縄風炊き込みご飯「ジューシー」は昼過ぎには売り切れることが多いため、午前中（11:00開店直後）の訪問が安心です。",
    "tip_en": "Their handmade Jushi (savory seasoned rice) frequently sells out by early afternoon, so aim for an 11:00 AM arrival right when doors open.",
    "categories": ["Café"]
  },
  {
    "id": "oki_p_31",
    "name": "首里そば",
    "name_ja": "首里そば",
    "name_en": "Shuri Soba",
    "category": "Café & Dining",
    "rating": "★4.6",
    "desc": "首里城近くの閑静な住宅街にある行列必至の沖縄そば専門店。澄んだ黄金色の鰹出汁と硬めに手打ちされた縮れ麺の完成度が際立つ。",
    "desc_ja": "首里城近くの閑静な住宅街にある行列必至の沖縄そば専門店。澄んだ黄金色の鰹出汁と硬めに手打ちされた縮れ麺の完成度が際立つ。",
    "desc_en": "A celebrated Naha soba shop near Shuri Castle, famed for its crystal-clear golden bonito broth and remarkably firm hand-pulled noodles.",
    "price": "首里そば（中）：約650円",
    "price_ja": "首里そば（中）：約650円",
    "price_en": "Soba ~¥650",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2195,
    "lng": 127.7212,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 営業時間は11:30〜14:00頃（麺がなくなり次第終了）の約2時間半のみ。首里城見学の前後に立ち寄るのが王道の観光ルートです。",
    "tip_ja": "💡 営業時間は11:30〜14:00頃（麺がなくなり次第終了）の約2時間半のみ。首里城見学の前後に立ち寄るのが王道の観光ルートです。",
    "tip_en": "Open strictly from 11:30 to around 14:00 until fresh noodle batches sell out. Pairs conveniently right before or after touring Shurijo Castle.",
    "categories": ["Café"]
  },
  {
    "id": "oki_p_32",
    "name": "ジャッキーステーキハウス",
    "name_ja": "ジャッキーステーキハウス",
    "name_en": "Jacks Steak House",
    "category": "Café & Dining",
    "rating": "★4.5",
    "desc": "1953年創業、アメリカ統治時代の面影をそのまま残す那覇屈指の老舗ステーキ店。熱々の鉄板で提供される赤身テンダーロインが名物。",
    "desc_ja": "1953年創業、アメリカ統治時代の面影をそのまま残す那覇屈指の老舗ステーキ店。熱々の鉄板で提供される赤身テンダーロインが名物。",
    "desc_en": "A legendary 1953 American-era steakhouse in Naha serving sizzling iron-plate tenderloin steaks, creamy mushroom soup, and retro diner charm.",
    "price": "テンダーロインステーキ：約2,900円〜",
    "price_ja": "テンダーロインステーキ：約2,900円〜",
    "price_en": "Steak ~¥2,900+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2128,
    "lng": 127.6743,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": True,
    "tip": "💡 特製No.1ステーキソースに醤油を少し垂らして食べるのが地元ウチナーンチュ流。深夜まで営業しておりフライト前後の食事にも便利です。",
    "tip_ja": "💡 特製No.1ステーキソースに醤油を少し垂らして食べるのが地元ウチナーンチュ流。深夜まで営業しておりフライト前後の食事にも便利です。",
    "tip_en": "Local patrons blend the tangy No.1 Steak Sauce with a splash of soy sauce. Stays open late into the evening for post-arrival late dinners.",
    "categories": ["Café", "Night"]
  },
  {
    "id": "oki_p_33",
    "name": "ポーたま 牧志市場店",
    "name_ja": "ポーたま 牧志市場店",
    "name_en": "Potama Makishi Market",
    "category": "Café & Dining",
    "rating": "★4.5",
    "desc": "沖縄のソウルフード「ポークたまごおにぎり」の専門店。注文を受けてから握る熱々のスパムと厚焼き卵の出来立ておにぎりが大人気。",
    "desc_ja": "沖縄のソウルフード「ポークたまごおにぎり」の専門店。注文を受けてから握る熱々のスパムと厚焼き卵の出来立ておにぎりが大人気。",
    "desc_en": "Popular grab-and-go specialty shop crafting made-to-order warm spam and fluffy egg onigiri sandwiches wrapped in roasted nori seaweed.",
    "price": "おにぎり：約390円〜",
    "price_ja": "おにぎり：約390円〜",
    "price_en": "Onigiri ~¥390+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2144,
    "lng": 127.6898,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 朝7:00からオープンしているため那覇宿泊時の朝食に最適。「ゴーヤの天ぷら」や「油みそ」など沖縄ならではの具材トッピングが格別です。",
    "tip_ja": "💡 朝7:00からオープンしているため那覇宿泊時の朝食に最適。「ゴーヤの天ぷら」や「油みそ」など沖縄ならではの具材トッピングが格別です。",
    "tip_en": "Opens early at 7:00 AM, making it the perfect morning breakfast stop before heading out on day road trips across the island.",
    "categories": ["Café"]
  },
  {
    "id": "oki_p_34",
    "name": "道の駅いとまん・お魚センター",
    "name_ja": "道の駅いとまん・お魚センター",
    "name_en": "Michi-no-Eki Itoman Fish Market",
    "category": "Shopping & Dining",
    "rating": "★4.5",
    "desc": "日本最南端の道の駅にある鮮魚市場。糸満漁港から直送されたマグロの刺身、生牡蠣、伊勢海老ウニ焼きなどをその場でバイキング感覚で食べ歩きできる。",
    "desc_ja": "日本最南端の道の駅にある鮮魚市場。糸満漁港から直送されたマグロの刺身、生牡蠣、伊勢海老ウニ焼きなどをその場でバイキング感覚で食べ歩きできる。",
    "desc_en": "Japan southernmost roadside station fish center, where visitors choose single skewers of grilled sea urchin lobster and fresh sashimi direct from the harbor.",
    "price": "刺身パック：約300円〜 / 海鮮丼：約1,000円〜",
    "price_ja": "刺身パック：約300円〜 / 海鮮丼：約1,000円〜",
    "price_en": "Seafood portions ~¥300-¥1,000+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1368,
    "lng": 127.6628,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 1貫100円前後の握り寿司や生ウニ焼きをトレーに好きなだけ取って店外の屋根付きテラスで味わえます。那覇空港から車で20分とアクセス良好。",
    "tip_ja": "💡 1貫100円前後の握り寿司や生ウニ焼きをトレーに好きなだけ取って店外の屋根付きテラスで味わえます。那覇空港から車で20分とアクセス良好。",
    "tip_en": "Assemble your custom sashimi lunch from individual vendor stalls and enjoy outdoor dining under shaded covered benches. Only 20 minutes from Naha Airport.",
    "categories": ["Shopping", "Café"]
  },
  {
    "id": "oki_p_35",
    "name": "ニライカナイ橋",
    "name_ja": "ニライカナイ橋",
    "name_en": "Nirai Kanai Bridge",
    "category": "Scenery & Drive",
    "rating": "★4.7",
    "desc": "南城市の山から海へ向かって大きく弧を描くループ橋。「ニライ橋」と「カナイ橋」が合わさった沖縄屈指の海絶景ドライブウェイ。",
    "desc_ja": "南城市の山から海へ向かって大きく弧を描くループ橋。「ニライ橋」と「カナイ橋」が合わさった沖縄屈指の海絶景ドライブウェイ。",
    "desc_en": "A spectacular sweeping S-curve coastal highway viaduct in Nanjo descending toward the Pacific, named after the mythical paradise beyond the horizon.",
    "price": "通行無料",
    "price_ja": "通行無料",
    "price_en": "Free toll-free drive",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1558,
    "lng": 127.8189,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": True,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 トンネルを抜けて海側（山から海へ下るルート）で走行すると、視界一面に太平洋がパッと広がり感動的なドライブが体験できます。",
    "tip_ja": "💡 トンネルを抜けて海側（山から海へ下るルート）で走行すると、視界一面に太平洋がパッと広がり感動的なドライブが体験できます。",
    "tip_en": "Drive downward from the inland plateau toward the coast; emerging through the tunnel reveals an instantaneous dramatic panorama of shimmering ocean waters.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_36",
    "name": "海中道路",
    "name_ja": "海中道路",
    "name_en": "Kaichu-Doro Mid-Sea Highway",
    "category": "Scenery & Drive",
    "rating": "★4.6",
    "desc": "うるま市の勝連半島と4つの離島を結ぶ全長4.7kmの海上道路。両サイドをエメラルドグリーンの浅瀬に囲まれた爽快なドライブルート。",
    "desc_ja": "うるま市の勝連半島と4つの離島を結ぶ全長4.7kmの海上道路。両サイドをエメラルドグリーンの浅瀬に囲まれた爽快なドライブルート。",
    "desc_en": "A scenic 4.7-kilometer causeway stretching across turquoise shallow waters in Uruma, linking Okinawa mainland with four peaceful outlying islands.",
    "price": "通行無料",
    "price_ja": "通行無料",
    "price_en": "Free toll-free road",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.3353,
    "lng": 127.9255,
    "rain": False,
    "kids": True,
    "shopping": True,
    "free": True,
    "top7": True,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 道路の中央にある「海の駅あやはし館」で休憩でき、歩道橋の上から真っ直ぐ伸びる海上ロードの美しい直線美を撮影できます。",
    "tip_ja": "💡 道路の中央にある「海の駅あやはし館」で休憩でき、歩道橋の上から真っ直ぐ伸びる海上ロードの美しい直線美を撮影できます。",
    "tip_en": "Stop midway at Ayahashi-kan roadside station to walk the pedestrian bridge for symmetrical aerial photos looking down the ocean roadway.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_37",
    "name": "浜比嘉島・シルミチュー",
    "name_ja": "浜比嘉島・シルミチュー",
    "name_en": "Hamahiga Island & Shirumichu",
    "category": "Landmark & Culture",
    "rating": "★4.7",
    "desc": "海中道路の先にある神々の住まう島。琉球開闢の祖「アマミキヨ」「シネリキヨ」が暮らしたとされる静謐な洞窟の霊場。",
    "desc_ja": "海中道路の先にある神々の住まう島。琉球開闢の祖「アマミキヨ」「シネリキヨ」が暮らしたとされる静謐な洞窟の霊場。",
    "desc_en": "A tranquil spiritual island reached via Kaichu-doro, revered as the dwelling ground of creation deities with sacred caves nestled inside coastal groves.",
    "price": "参拝自由",
    "price_ja": "参拝自由",
    "price_en": "Free admission",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.3128,
    "lng": 127.9625,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 108段の石段を登った先にある鍾乳洞の拝所は子宝・安産の祈願所としても知られます。島内には赤瓦の古民家集落が今も色濃く残ります。",
    "tip_ja": "💡 108段の石段を登った先にある鍾乳洞の拝所は子宝・安産の祈願所としても知られます。島内には赤瓦の古民家集落が今も色濃く残ります。",
    "tip_en": "Ascend the 108 stone steps through subtropical trees to reach the sacred grotto. The island retains traditional red-tile roofs and stone walls.",
    "categories": ["Landmark"]
  },
  {
    "id": "oki_p_38",
    "name": "知念岬公園",
    "name_ja": "知念岬公園",
    "name_en": "Chinen Cape Park",
    "category": "Scenery & Park",
    "rating": "★4.6",
    "desc": "南城市の東端、太平洋に突き出た美しい緑の岬。250度の水平線と神の島「久高島」を一望できる開放感あふれる絶景スポット。",
    "desc_ja": "南城市の東端、太平洋に突き出た美しい緑の岬。250度の水平線と神の島「久高島」を一望できる開放感あふれる絶景スポット。",
    "desc_en": "A verdant promontory park in Nanjo jutting into the cobalt Pacific, commanding 250-degree ocean views across to sacred Kudaka Island.",
    "price": "入園無料・駐車場無料",
    "price_ja": "入園無料・駐車場無料",
    "price_en": "Free park admission",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1661,
    "lng": 127.8306,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 世界遺産の斎場御嶽（せーふぁうたき）から車でわずか3分。赤瓦の東屋や整備された遊歩道があり、日の出の絶景スポットとしても知られます。",
    "tip_ja": "💡 世界遺産の斎場御嶽（せーふぁうたき）から車でわずか3分。赤瓦の東屋や整備された遊歩道があり、日の出の絶景スポットとしても知られます。",
    "tip_en": "Located just 3 minutes from Sefa-Utaki. The manicured coastal boardwalk with Ryukyuan pavilions makes it a prime sunrise viewing location.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_39",
    "name": "辺戸岬",
    "name_ja": "辺戸岬",
    "name_en": "Cape Hedo",
    "category": "Scenery & Nature",
    "rating": "★4.5",
    "desc": "沖縄本島の最北端に位置する断崖絶壁の岬。東シナ海と太平洋の荒波が激しくぶつかり合うダイナミックな景観と雄大な自然を体感できる。",
    "desc_ja": "沖縄本島の最北端に位置する断崖絶壁の岬。東シナ海と太平洋の荒波が激しくぶつかり合うダイナミックな景観と雄大な自然を体感できる。",
    "desc_en": "The northernmost tip of Okinawa Main Island, where dramatic limestone cliffs overlook the turbulent confluence of the East China Sea and the Pacific.",
    "price": "見学自由・駐車場無料",
    "price_ja": "見学自由・駐車場無料",
    "price_en": "Free admission",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.8722,
    "lng": 128.2589,
    "rain": False,
    "kids": True,
    "shopping": True,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 晴れた日には約22km先の鹿児島県与論島が水平線上にくっきり見えます。岬の観光案内所「HEAD LINE」の2階カフェからの展望も爽快です。",
    "tip_ja": "💡 晴れた日には約22km先の鹿児島県与論島が水平線上にくっきり見えます。岬の観光案内所「HEAD LINE」の2階カフェからの展望も爽快です。",
    "tip_en": "On clear sunny days, Yoron Island in Kagoshima is visible across the horizon. Stop at the modern visitor center cafe for panoramic upper-deck views.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_40",
    "name": "瀬底島・瀬底ビーチ",
    "name_ja": "瀬底島・瀬底ビーチ",
    "name_en": "Sesoko Island & Sesoko Beach",
    "category": "Scenery & Beach",
    "rating": "★4.6",
    "desc": "瀬底大橋を渡ってアクセスできる離島。約800mにわたる白砂の天然ビーチと、本島屈指の透明度を誇るエメラルドブルーの遠浅の海が広がる。",
    "desc_ja": "瀬底大橋を渡ってアクセスできる離島。約800mにわたる白砂の天然ビーチと、本島屈指の透明度を誇るエメラルドブルーの遠浅の海が広がる。",
    "desc_en": "A bridge-accessible island near Motobu boasting an 800-meter pristine white-sand beach renowned for supreme water clarity and sunset vistas.",
    "price": "遊泳無料（シャワー・更衣室：有料）",
    "price_ja": "遊泳無料（シャワー・更衣室：有料）",
    "price_en": "Free beach access",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.6433,
    "lng": 127.8542,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 遠浅で波が穏やかなためシュノーケリングで色鮮やかな熱帯魚を間近に観察できます。伊江島に沈む夕日の美しさは本島トップクラス。",
    "tip_ja": "💡 遠浅で波が穏やかなためシュノーケリングで色鮮やかな熱帯魚を間近に観察できます。伊江島に沈む夕日の美しさは本島トップクラス。",
    "tip_en": "Gentle shallow waters offer close-up snorkeling with colorful tropical reef fish. Sunset over nearby Ie Island provides iconic golden-hour photo opportunities.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_41",
    "name": "古宇利島 ティーヌ浜（ハートロック）",
    "name_ja": "古宇利島 ティーヌ浜（ハートロック）",
    "name_en": "Tinu Beach Heart Rock",
    "category": "Scenery & Beach",
    "rating": "★4.5",
    "desc": "古宇利島の北側にある隠れ家的な天然ビーチ。長い年月をかけて波の浸食で削られハートの形になった2つの奇岩「ハートロック」が名所。",
    "desc_ja": "古宇利島の北側にある隠れ家的な天然ビーチ。長い年月をかけて波の浸食で削られハートの形になった2つの奇岩「ハートロック」が名所。",
    "desc_en": "A secluded cove on the northern coast of Kouri Island famous for twin naturally sculpted coral limestone formations resembling hearts.",
    "price": "見学自由（民間駐車場：約100〜300円）",
    "price_ja": "見学自由（民間駐車場：約100〜300円）",
    "price_en": "Free beach access (Parking ~¥300)",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.7119,
    "lng": 128.0267,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 2つの岩が重なり合う角度から見ると、岩と岩の隙間に綺麗なハート型が浮かび上がります。足元が砂利や岩場なので歩きやすいサンダルが必須です。",
    "tip_ja": "💡 2つの岩が重なり合う角度から見ると、岩と岩の隙間に綺麗なハート型が浮かび上がります。足元が砂利や岩場なので歩きやすいサンダルが必須です。",
    "tip_en": "Position yourself so the two rocks visually overlap to form a complete heart silhouette between them. Wear sturdy footwear on the rocky beach path.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_42",
    "name": "ブセナ海中公園・海中展望塔",
    "name_ja": "ブセナ海中公園・海中展望塔",
    "name_en": "Busena Marine Park & Underwater Observatory",
    "category": "Museum & Marine",
    "rating": "★4.5",
    "desc": "名護市部瀬名岬の沖合170mにある海中展望塔。服を着たままらせん階段を降りて水深4mの窓から熱帯魚やサンゴ礁を間近に観察できる。",
    "desc_ja": "名護市部瀬名岬の沖合170mにある海中展望塔。服を着たままらせん階段を降りて水深4mの窓から熱帯魚やサンゴ礁を間近に観察できる。",
    "desc_en": "An offshore observation tower in Nago where visitors descend a spiral staircase into a dry 360-degree viewing chamber 4 meters below the sea surface.",
    "price": "展望塔大人：1,050円 / クジラ型グラスボート：1,560円",
    "price_ja": "展望塔大人：1,050円 / クジラ型グラスボート：1,560円",
    "price_en": "Observatory: ¥1,050",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.5292,
    "lng": 127.9308,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 雨の日や海に入れない季節でも濡れずに沖縄の海中を楽しめる貴重な施設。底がガラスになったクジラ型グラス底ボートとのセット券がお得です。",
    "tip_ja": "💡 雨の日や海に入れない季節でも濡れずに沖縄の海中を楽しめる貴重な施設。底がガラスになったクジラ型グラス底ボートとのセット券がお得です。",
    "tip_en": "Ideal for non-swimmers, seniors, and rainy days. Pair with the whale-shaped glass-bottom catamaran for an immersive marine exploration combo ticket.",
    "categories": ["Scenery", "Kids"]
  },
  {
    "id": "oki_p_43",
    "name": "ガンガラーの谷",
    "name_ja": "ガンガラーの谷",
    "name_en": "Valley of Gangala",
    "category": "Nature & Adventure",
    "rating": "★4.7",
    "desc": "数十万年前の鍾乳洞が崩壊して生まれた太古の亜熱帯の谷。樹齢150年を超える巨大な「大主ガジュマル」や古代人の居住跡が残る聖域。",
    "desc_ja": "数十万年前の鍾乳洞が崩壊して生まれた太古の亜熱帯の谷。樹齢150年を超える巨大な「大主ガジュマル」や古代人の居住跡が残る聖域。",
    "desc_en": "A primordial subtropical valley formed by collapsed limestone caverns in Nanjo, home to 150-year-old walking banyan trees and prehistoric human excavation sites.",
    "price": "ガイドツアー：2,500円（保護者同伴の中学生以下無料）",
    "price_ja": "ガイドツアー：2,500円（保護者同伴の中学生以下無料）",
    "price_en": "Guided Tour: ¥2,500",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1428,
    "lng": 127.7514,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 谷の散策は完全予約制の専任ガイドツアー（約80分）のみ。ツアー受付場所である天然鍾乳洞内の「ケイブカフェ」は神秘的な空間です。",
    "tip_ja": "💡 谷の散策は完全予約制の専任ガイドツアー（約80分）のみ。ツアー受付場所である天然鍾乳洞内の「ケイブカフェ」は神秘的な空間です。",
    "tip_en": "Exploration requires reserving the 80-minute walking guided tour in advance. The entrance features Cave Cafe set beneath towering natural stalactites.",
    "categories": ["Scenery", "Landmark"]
  },
  {
    "id": "oki_p_44",
    "name": "東南植物楽園",
    "name_ja": "東南植物楽園",
    "name_en": "Southeast Botanical Gardens",
    "category": "Nature & Park",
    "rating": "★4.5",
    "desc": "沖縄市にある日本最大級の屋外植物園。約1,300種、5万株以上の熱帯・亜熱帯植物が茂り、カピバラやリスザルとのふれあい体験も人気。",
    "desc_ja": "沖縄市にある日本最大級の屋外植物園。約1,300種、5万株以上の熱帯・亜熱帯植物が茂り、カピバラやリスザルとのふれあい体験も人気。",
    "desc_en": "A 100-acre tropical paradise garden in Okinawa City housing over 1,300 plant species, towering Alexander palm groves, and interactive capybara petting areas.",
    "price": "大人：約1,540円 / 小中学生：約800円",
    "price_ja": "大人：約1,540円 / 小中学生：約800円",
    "price_en": "Adult: ¥1,540 / Child: ¥800",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.3764,
    "lng": 127.8067,
    "rain": False,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": True,
    "tip": "💡 冬季（10月下旬〜5月）に開催される「沖縄南国イルミネーション」は全国イルミネーションアワードで日本一を受賞した圧巻の光の祭典です。",
    "tip_ja": "💡 冬季（10月下旬〜5月）に開催される「沖縄南国イルミネーション」は全国イルミネーションアワードで日本一を受賞した圧巻の光の祭典です。",
    "tip_en": "Their winter illuminations (late Oct to May) have won #1 in national Japanese illumination rankings, transforming the palm groves into a wonderland.",
    "categories": ["Scenery", "Kids", "Night"]
  },
  {
    "id": "oki_p_45",
    "name": "ネオパークオキナワ",
    "name_ja": "ネオパークオキナワ",
    "name_en": "Neo Park Okinawa",
    "category": "Theme Park & Zoo",
    "rating": "★4.5",
    "desc": "名護市にある広大な動植物自然公園。ネットで囲まれたフライングケージ内でフラミンゴや珍しい鳥たちが自由に放し飼いされている。",
    "desc_ja": "名護市にある広大な動植物自然公園。ネットで囲まれたフライングケージ内でフラミンゴや珍しい鳥たちが自由に放し飼いされている。",
    "desc_en": "A sprawling open-range subtropical animal park in Nago featuring massive walk-through aviaries where hundreds of exotic waterfowls roam freely.",
    "price": "大人：1,300円 / 小人：700円",
    "price_ja": "大人：1,300円 / 小人：700円",
    "price_en": "Adult: ¥1,300 / Child: ¥700",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.6192,
    "lng": 127.9944,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 かつて沖縄を走っていた軽便鉄道を実物の3/4スケールで再現した「沖縄軽便鉄道」に乗って園内を一周するトレインツアーが家族連れに大人気です。",
    "tip_ja": "💡 かつて沖縄を走っていた軽便鉄道を実物の3/4スケールで再現した「沖縄軽便鉄道」に乗って園内を一周するトレインツアーが家族連れに大人気です。",
    "tip_en": "Board the replica vintage train (modeled on the historical pre-war Okinawa Railway) for an informative narrated loop through animal biomes.",
    "categories": ["Kids"]
  },
  {
    "id": "oki_p_46",
    "name": "琉球村",
    "name_ja": "琉球村",
    "name_en": "Ryukyu Mura Cultural Village",
    "category": "Culture & Theme Park",
    "rating": "★4.5",
    "desc": "恩納村にある体験型テーマパーク。築100年以上の沖縄各地の古民家を移築・復元し、エイサー演舞や三線体験、伝統菓子作りが楽しめる。",
    "desc_ja": "恩納村にある体験型テーマパーク。築100年以上の沖縄各地の古民家を移築・復元し、エイサー演舞や三線体験、伝統菓子作りが楽しめる。",
    "desc_en": "A preserved cultural village in Onna featuring relocated century-old heritage thatched-roof houses, live Eisa taiko drumming, and folk crafts.",
    "price": "大人：約1,500円 / 高校生：約1,200円 / 小人：約600円",
    "price_ja": "大人：約1,500円 / 高校生：約1,200円 / 小人：約600円",
    "price_en": "Adult: ¥1,500",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.4317,
    "lng": 127.7844,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 毎日開催される力強い「道じゅねー（エイサーパレード）」は必見。雨天時でも全天候型ドームや古民家の軒下で各種体験が可能です。",
    "tip_ja": "💡 毎日開催される力強い「道じゅねー（エイサーパレード）」は必見。雨天時でも全天候型ドームや古民家の軒下で各種体験が可能です。",
    "tip_en": "Do not miss the vibrant daily parade featuring folk dancing and dynamic taiko drumming. The central covered pavilion ensures activities run even in rain.",
    "categories": ["Landmark", "Kids"]
  },
  {
    "id": "oki_p_47",
    "name": "中城城跡",
    "name_ja": "中城城跡",
    "name_en": "Nakagusuku Castle Ruins",
    "category": "Landmark & Heritage",
    "rating": "★4.6",
    "desc": "世界遺産「琉球王国のグスク及び関連遺産群」の一つ。ペリー提督の探検隊が高度な石積み技術を絶賛した、美しいアーチ門と城壁が残る名城。",
    "desc_ja": "世界遺産「琉球王国のグスク及び関連遺産群」の一つ。ペリー提督の探検隊が高度な石積み技術を絶賛した、美しいアーチ門と城壁が残る名城。",
    "desc_en": "A UNESCO World Heritage cliff-top fortress acclaimed by Commodore Perry in 1853 for its sophisticated arched masonry and commanding panoramic views.",
    "price": "大人：400円 / 中高生：300円 / 小学生：200円",
    "price_ja": "大人：400円 / 中高生：300円 / 小学生：200円",
    "price_en": "Adult: ¥400",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2844,
    "lng": 127.8019,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 標高約160mの高台にあり、東シナ海と中城湾（太平洋）の両方を一望できます。カート送迎付きで歩きやすく家族連れにもおすすめです。",
    "tip_ja": "💡 標高約160mの高台にあり、東シナ海と中城湾（太平洋）の両方を一望できます。カート送迎付きで歩きやすく家族連れにもおすすめです。",
    "tip_en": "Perched at 160 meters elevation, it simultaneously overlooks both the East China Sea and the Pacific. Free electric golf carts take you from the ticket booth up the hill.",
    "categories": ["Landmark", "Scenery"]
  },
  {
    "id": "oki_p_48",
    "name": "壺屋やちむん通り",
    "name_ja": "壺屋やちむん通り",
    "name_en": "Tsuboya Yachimun Pottery Street",
    "category": "Shopping & Culture",
    "rating": "★4.5",
    "desc": "那覇市の国際通りからすぐの石畳の通り。330年以上の伝統を誇る窯元や陶器ギャラリー、やちむんカフェが約400mにわたって並ぶ。",
    "desc_ja": "那覇市の国際通りからすぐの石畳の通り。330年以上の伝統を誇る窯元や陶器ギャラリー、やちむんカフェが約400mにわたって並ぶ。",
    "desc_en": "A historic 400-meter paved cobblestone boulevard in Naha lined with multi-generational kilns, ceramic artist studios, and traditional pottery cafes.",
    "price": "散策自由",
    "price_ja": "散策自由",
    "price_en": "Free to stroll",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2125,
    "lng": 127.6917,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 温かみのある伝統の唐草模様からモダンな日常使いの器まで揃います。通り沿いの「那覇市立壺屋焼物博物館」で歴史を学んでから巡るとより深く楽しめます。",
    "tip_ja": "💡 温かみのある伝統の唐草模様からモダンな日常使いの器まで揃います。通り沿いの「那覇市立壺屋焼物博物館」で歴史を学んでから巡るとより深く楽しめます。",
    "tip_en": "Explore artisan stores offering everything from classic arabesque patterns to contemporary pastel dishes. The small Tsuboya Pottery Museum provides rich historic context.",
    "categories": ["Shopping", "Landmark"]
  },
  {
    "id": "oki_p_49",
    "name": "首里金城町石畳道",
    "name_ja": "首里金城町石畳道",
    "name_en": "Shuri Kinjo-cho Stone-Paved Path",
    "category": "Landmark & Historic",
    "rating": "★4.5",
    "desc": "琉球王国時代に首里城と那覇港を結んだ軍事用幹線道路の一部。琉球石灰岩が敷き詰められた約300mの石畳道と沖縄の赤瓦家屋が残る古道。",
    "desc_ja": "琉球王国時代に首里城と那覇港を結んだ軍事用幹線道路の一部。琉球石灰岩が敷き詰められた約300mの石畳道と沖縄の赤瓦家屋が残る古道。",
    "desc_en": "A serene 300-meter limestone-paved highway dating from 1522 during the Golden Age of the Ryukyu Kingdom, bordered by red-tiled village homes.",
    "price": "散策自由",
    "price_ja": "散策自由",
    "price_en": "Free to stroll",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2147,
    "lng": 127.7153,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 途中の脇道を入ると樹齢300年以上の「金城町の大アカギ（国の天然記念物）」が静かに佇むパワースポットがあります。雨の日は石畳が滑りやすいので注意。",
    "tip_ja": "💡 途中の脇道を入ると樹齢300年以上の「金城町の大アカギ（国の天然記念物）」が静かに佇むパワースポットがあります。雨の日は石畳が滑りやすいので注意。",
    "tip_en": "Detour halfway down into a hidden forest clearing to behold the Sacred Giant Akagi Tree (300+ years old). Worn limestone surfaces can be slippery when damp.",
    "categories": ["Landmark"]
  },
  {
    "id": "oki_p_50",
    "name": "沖縄県立博物館・美術館（おきみゅー）",
    "name_ja": "沖縄県立博物館・美術館（おきみゅー）",
    "name_en": "Okinawa Prefectural Museum & Art Museum (OkiMu)",
    "category": "Museum & Art",
    "rating": "★4.5",
    "desc": "那覇市おもろまちにある沖縄の城（グスク）をイメージした白亜の巨大複合文化施設。沖縄の自然・歴史・民俗と現代アートを網羅。",
    "desc_ja": "那覇市おもろまちにある沖縄の城（グスク）をイメージした白亜の巨大複合文化施設。沖縄の自然・歴史・民俗と現代アートを網羅。",
    "desc_en": "A landmark cultural museum in Naha designed after ancient Ryukyuan gusuku fortresses, showcasing comprehensive island geology, kingdom history, and modern arts.",
    "price": "博物館常設展：大人530円 / 高大生：270円",
    "price_ja": "博物館常設展：大人530円 / 高大生：270円",
    "price_en": "Museum Entry: ¥530",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2278,
    "lng": 127.6931,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 ゆいレール「おもろまち駅」から徒歩10分。雨の日の観光拠点として最適で、体験学習室「ふれあい体験室」では昔の民具や楽器に直接触れられます。",
    "tip_ja": "💡 ゆいレール「おもろまち駅」から徒歩10分。雨の日の観光拠点として最適で、体験学習室「ふれあい体験室」では昔の民具や楽器に直接触れられます。",
    "tip_en": "Located 10 minutes from Omoromachi monorail station. An unrivaled rainy-day refuge with interactive hands-on heritage learning rooms for all ages.",
    "categories": ["Museum"]
  }
]

combined = existing + new_spots
print(f"Successfully combined: {len(existing)} existing + {len(new_spots)} new = {len(combined)} spots total.")

with open('data/cities/okinawa.json', 'w', encoding='utf-8') as f:
    json.dump(combined, f, indent=2, ensure_ascii=False)
