#!/usr/bin/env python3
import json

with open('data/cities/okinawa.json', 'r', encoding='utf-8') as f:
    spots = json.load(f)

# Update existing oki_p_8 (平和祈念公園) TIPS to enrich with 子ども広場「命の卵」
for s in spots:
    if s['id'] == 'oki_p_8':
        s['tip'] = "💡 崖上から太平洋を見渡す景色は圧巻。広大な敷地内には平和祈念資料館のほか、南側の子ども広場「命の卵」に巨大トランポリンや大型複合遊具があり、子連れ休憩にも重宝します。"
        s['tip_ja'] = s['tip']
    elif s['id'] == 'oki_p_11':
        s['tip'] = "💡 沖縄唯一の登れる参観灯台で360度パノラマが爽快。岬入口の「いこいの広場」には日本一巨大な残波大獅子（高さ8.7m）や遊具、ヤギふれあい広場があり立ち寄り必須です。"
        s['tip_ja'] = s['tip']

new_batch = [
  {
    "id": "oki_p_51",
    "name": "DMMかりゆし水族館（イーアス沖縄豊崎）",
    "name_ja": "DMMかりゆし水族館（イーアス沖縄豊崎）",
    "name_en": "DMM Kariyushi Aquarium (iias Toyosaki)",
    "category": "Museum & Marine",
    "rating": "★4.6",
    "desc": "那覇空港から車で約20分、イーアス沖縄豊崎に併設された最新エンタメ水族館。透明なガラス床の上を歩く大水槽や、ナマケモノ・カワウソとの至近距離ふれあいが人気。",
    "desc_ja": "那覇空港から車で約20分、イーアス沖縄豊崎に併設された最新エンタメ水族館。透明なガラス床の上を歩く大水槽や、ナマケモノ・カワウソとの至近距離ふれあいが人気。",
    "desc_en": "A cutting-edge interactive aquarium just 20 minutes from Naha Airport, featuring glass-floor walk-above tanks, immersive soundscapes, and close encounters with sloths and penguins.",
    "price": "大人2,400円 / 中人1,500円 / 小人1,000円",
    "price_ja": "大人2,400円 / 中人1,500円 / 小人1,000円",
    "price_en": "Adult: ¥2,400 / Youth: ¥1,500 / Child: ¥1,000",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1583,
    "lng": 127.6536,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": True,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 完全屋内のため雨の日やフライト前後のすきま時間に最適。直結の大型モール「イーアス沖縄豊崎」でのお買い物やお食事、屋上恐竜パークもまとめて楽しめます。",
    "tip_ja": "💡 完全屋内のため雨の日やフライト前後のすきま時間に最適。直結の大型モール「イーアス沖縄豊崎」でのお買い物やお食事、屋上恐竜パークもまとめて楽しめます。",
    "tip_en": "Fully indoor and ideal for rainy days or final flight buffer hours. Connects directly to iias Okinawa Toyosaki shopping mall with rooftop attractions.",
    "categories": ["Museum", "Kids", "Shopping"]
  },
  {
    "id": "oki_p_52",
    "name": "沖縄こどもの国",
    "name_ja": "沖縄こどもの国",
    "name_en": "Okinawa Zoo & Museum (Kodomo no Kuni)",
    "category": "Theme Park & Zoo",
    "rating": "★4.6",
    "desc": "沖縄市にある県内唯一の本格動物園と体験型科学館「ワンダーミュージアム」の複合施設。ゾウやキリン、島ヤギへのエサやり体験や知育型ハンズオン展示が充実。",
    "desc_ja": "沖縄市にある県内唯一の本格動物園と体験型科学館「ワンダーミュージアム」の複合施設。ゾウやキリン、島ヤギへのエサやり体験や知育型ハンズオン展示が充実。",
    "desc_en": "Okinawa's premier zoological park and hands-on children's science discovery museum in Okinawa City, featuring Asian elephants, giraffes, and creative workshops.",
    "price": "大人1,000円 / 中高生500円 / 4歳〜小学生200円",
    "price_ja": "大人1,000円 / 中高生500円 / 4歳〜小学生200円",
    "price_en": "Adult: ¥1,000 / Child: ¥200",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.3267,
    "lng": 127.7972,
    "rain": True,
    "kids": True,
    "shopping": False,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 地下にある「ワンダーミュージアム」は冷房完備の完全屋内型で、猛暑や雨の日でも子どもが夢中で科学工作や音の実験を楽しめる神スポットです。",
    "tip_ja": "💡 地下にある「ワンダーミュージアム」は冷房完備の完全屋内型で、猛暑や雨の日でも子どもが夢中で科学工作や音の実験を楽しめる神スポットです。",
    "tip_en": "The indoor Wonder Museum basement offers air-conditioned creative physics, optical, and sound puzzle installations, unbeatable for rainy or hot afternoons.",
    "categories": ["Kids", "Museum"]
  },
  {
    "id": "oki_p_53",
    "name": "中城公園（なかぐすくこうえん）",
    "name_ja": "中城公園（なかぐすくこうえん）",
    "name_en": "Nakagusuku Park (Giant Playground)",
    "category": "Nature & Park",
    "rating": "★4.6",
    "desc": "中城村・北中城村にまたがる県内最大級の県営総合公園。巨大な白トランポリン「ふわふわドーム」やすり鉢状の大型アスレチック複合遊具が無料で遊び放題。",
    "desc_ja": "中城村・北中城村にまたがる県内最大級の県営総合公園。巨大な白トランポリン「ふわふわドーム」やすり鉢状の大型アスレチック複合遊具が無料で遊び放題。",
    "desc_en": "One of Okinawa's largest free municipal adventure parks, celebrated for its colossal bouncy cloud dome, mega slides, and multi-level climbing towers.",
    "price": "入場無料・駐車場無料",
    "price_ja": "入場無料・駐車場無料",
    "price_en": "Free park admission",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2956,
    "lng": 127.7892,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 西側駐車場が大型遊具広場に直結していて一番便利です。幼児向けエリアと高学年向け大型遊具がしっかり分かれているため小さな子ども連れでも安心。",
    "tip_ja": "💡 西側駐車場が大型遊具広場に直結していて一番便利です。幼児向けエリアと高学年向け大型遊具がしっかり分かれているため小さな子ども連れでも安心。",
    "tip_en": "Park at the West Parking Lot for direct steps to the giant slide complex. Features distinct toddler and big-kid play zones with shaded picnic pergolas.",
    "categories": ["Kids", "Scenery"]
  },
  {
    "id": "oki_p_54",
    "name": "ブルーシール アイスパーク",
    "name_ja": "ブルーシール アイスパーク",
    "name_en": "Blue Seal Ice Park",
    "category": "Café & Culture",
    "rating": "★4.5",
    "desc": "浦添市牧港の本店隣に誕生したアイス体験ミュージアム。冷凍庫体験やブルーシールの歴史を学び、オリジナルアイスバー作り体験（要予約）ができる。",
    "desc_ja": "浦添市牧港の本店隣に誕生したアイス体験ミュージアム。冷凍庫体験やブルーシールの歴史を学び、オリジナルアイスバー作り体験（要予約）ができる。",
    "desc_en": "A colorful interactive ice cream museum next to the Makiminato flagship store, where guests design, coat, and decorate their own custom ice cream bars.",
    "price": "見学無料 / アイス作り体験：1人1,800円（要予約）",
    "price_ja": "見学無料 / アイス作り体験：1人1,800円（要予約）",
    "price_en": "Entry free / DIY bar workshop: ¥1,800",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.2625,
    "lng": 127.7197,
    "rain": True,
    "kids": True,
    "shopping": True,
    "free": False,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 マイナス20度の冷凍庫体験やカラフルな撮影スポットが満載。体験予約がなくても隣のレトロアメリカンな直営店で限定アイスを楽しめます。",
    "tip_ja": "💡 マイナス20度の冷凍庫体験やカラフルな撮影スポットが満載。体験予約がなくても隣のレトロアメリカンな直営店で限定アイスを楽しめます。",
    "tip_en": "Step into the minus-20-degree deep-freeze simulation chamber. Even without reservations, enjoy retro 1960s parlor booths at the flagship shop next door.",
    "categories": ["Kids", "Café"]
  },
  {
    "id": "oki_p_55",
    "name": "豊崎美らSUNビーチ",
    "name_ja": "豊崎美らSUNビーチ",
    "name_en": "Toyosaki Chura-Sun Beach",
    "category": "Scenery & Beach",
    "rating": "★4.5",
    "desc": "豊見城市にある全長約700mの県内最大級の人工ビーチ。空港から車で15分、クラゲネットと監視員完備で遊泳やBBQ、頭上を通る飛行機ウォッチングが楽しめる。",
    "desc_ja": "豊見城市にある全長約700mの県内最大級の人工ビーチ。空港から車で15分、クラゲネットと監視員完備で遊泳やBBQ、頭上を通る飛行機ウォッチングが楽しめる。",
    "desc_en": "A 700-meter manicured recreation beach near Naha Airport equipped with jellyfish safety nets, lifeguards, sea-view BBQ lawns, and thrilling low-flying aircraft views.",
    "price": "遊泳無料・シャワー利用有料",
    "price_ja": "遊泳無料・シャワー利用有料",
    "price_en": "Free beach access",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1556,
    "lng": 127.6508,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 那覇空港の着陸航路の下にあるため、エメラルドの海を背景に巨大な旅客機が間近に迫る圧巻の飛行機写真が撮れる人気撮影地です。",
    "tip_ja": "💡 那覇空港の着陸航路の下にあるため、エメラルドの海を背景に巨大な旅客機が間近に迫る圧巻の飛行機写真が撮れる人気撮影地です。",
    "tip_en": "Directly situated under Naha Airport's landing corridor, offering world-class aviation photo spots with jumbo jets roaring across turquoise ocean backdrops.",
    "categories": ["Scenery", "Kids"]
  },
  {
    "id": "oki_p_56",
    "name": "奥武島（おうじま）",
    "name_ja": "奥武島（おうじま）",
    "name_en": "Ojima Island",
    "category": "Shopping & Culture",
    "rating": "★4.6",
    "desc": "南城市にある周囲約1.7km、本島から短い橋で渡れる漁業の島。名物「中本鮮魚てんぷら店」「大城てんぷら店」の揚げたて沖縄天ぷら食べ歩きと猫たちが名物。",
    "desc_ja": "南城市にある周囲約1.7km、本島から短い橋で渡れる漁業の島。名物「中本鮮魚てんぷら店」「大城てんぷら店」の揚げたて沖縄天ぷら食べ歩きと猫たちが名物。",
    "desc_en": "A tiny bridge-connected fishing islet in Nanjo renowned throughout Japan for piping-hot tempura fritters (squid, mozuku seaweed, local whitefish) and resident island cats.",
    "price": "天ぷら1個：約100〜120円",
    "price_ja": "天ぷら1個：約100〜120円",
    "price_en": "Tempura skewers ~¥100 each",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.1292,
    "lng": 127.7725,
    "rain": False,
    "kids": True,
    "shopping": True,
    "free": True,
    "top7": False,
    "hiddenGem": False,
    "is_night_spot": False,
    "tip": "💡 橋を渡ってすぐ右手の中本鮮魚店、島の奥にある大城てんぷら店の食べ比べが定番。サクサク衣のもずく天ぷらは揚げたて熱々が絶品です。",
    "tip_ja": "💡 橋を渡ってすぐ右手の中本鮮魚店、島の奥にある大城てんぷら店の食べ比べが定番。サクサク衣のもずく天ぷらは揚げたて熱々が絶品です。",
    "tip_en": "Compare Nakamoto Tempura right at the bridge crossing and Oshiro Tempura further inland. The crispy thick-battered mozuku seaweed fritter is best devoured hot on the sea wall.",
    "categories": ["Shopping", "Café"]
  },
  {
    "id": "oki_p_57",
    "name": "星野リゾート バンタカフェ",
    "name_ja": "星野リゾート バンタカフェ",
    "name_en": "Hoshino Resorts Banta Cafe",
    "category": "Café & Dining",
    "rating": "★4.6",
    "desc": "読谷村の海岸線に広がる国内最大級の海カフェ。入江に沿った自然の地形を活かし、崖の上テラス、岩場のデッキ、浜辺のラウンジなど4つのエリアから海を一望。",
    "desc_ja": "読谷村の海岸線に広がる国内最大級の海カフェ。入江に沿った自然の地形を活かし、崖の上テラス、岩場のデッキ、浜辺のラウンジなど4つのエリアから海を一望。",
    "desc_en": "One of Japan's largest sea cafes in Yomitan by Hoshino Resorts, built along natural coastal bluffs with four scenic zones including cliff terraces and beachfront tatami pavilions.",
    "price": "ドリンク・スイーツ：約800円〜",
    "price_ja": "ドリンク・スイーツ：約800円〜",
    "price_en": "Drinks ~¥800+",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.4097,
    "lng": 127.7208,
    "rain": True,
    "kids": False,
    "shopping": False,
    "free": False,
    "top7": True,
    "hiddenGem": False,
    "is_night_spot": True,
    "tip": "💡 夕日の時間帯は水平線に沈む太陽が息をのむ美しさ。海辺のテラス席に寝転がりながら「ぶくぶくジュレソーダ」を味わうひとときは極上のリゾート体験です。",
    "tip_ja": "💡 夕日の時間帯は水平線に沈む太陽が息をのむ美しさ。海辺のテラス席に寝転がりながら「ぶくぶくジュレソーダ」を味わうひとときは極上のリゾート体験です。",
    "tip_en": "Prime sunset vantage point in Yomitan. Sip on traditional bubbly Bukubuku Jelly Soda while lounging on shaded semi-outdoor beach tatami daybeds.",
    "categories": ["Café", "Scenery", "Night"]
  },
  {
    "id": "oki_p_58",
    "name": "具志川城跡（糸満市）",
    "name_ja": "具志川城跡（糸満市）",
    "name_en": "Gushikawa Castle Ruins (Itoman)",
    "category": "Landmark & Historic",
    "rating": "★4.6",
    "desc": "本島南端の喜屋武岬近く、東シナ海に突き出た断崖絶壁に築かれた古城跡。荒波が打ち寄せる三方を海に囲まれた壮大な城壁と海景が広がる国の史跡。",
    "desc_ja": "本島南端の喜屋武岬近く、東シナ海に突き出た断崖絶壁に築かれた古城跡。荒波が打ち寄せる三方を海に囲まれた壮大な城壁と海景が広がる国の史跡。",
    "desc_en": "A majestic National Historic gusuku perched atop sheer ocean promontory cliffs near Cape Kyan in Itoman, bordered on three sides by crashing East China Sea waves.",
    "price": "見学無料・駐車場無料",
    "price_ja": "見学無料・駐車場無料",
    "price_en": "Free admission",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "city",
    "lat": 26.0792,
    "lng": 127.6756,
    "rain": False,
    "kids": False,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 観光客が少なく波の音だけが響く静寂の絶景スポット。城壁の隙間から海へと通じる「火吹き穴」など独特の構造が見学できます。",
    "tip_ja": "💡 観光客が少なく波の音だけが響く静寂の絶景スポット。城壁の隙間から海へと通じる「火吹き穴」など独特の構造が見学できます。",
    "tip_en": "Free of tour buses with only ocean breezes and crashing surf. Inspect the mysterious vertical blowhole tunnel piercing straight from the fortress floor down to the tide.",
    "categories": ["Landmark", "Scenery"]
  },
  {
    "id": "oki_p_59",
    "name": "古宇利島 トケイ浜",
    "name_ja": "古宇利島 トケイ浜",
    "name_en": "Tokei Beach (Kouri Island)",
    "category": "Scenery & Beach",
    "rating": "★4.6",
    "desc": "古宇利島の北端、ティーヌ浜の東側に位置する天然の穴場ビーチ。円筒状に穴の空いた巨大な奇岩「ポットホール（円筒状空洞群）」と遠浅のサンゴ礁が広がる。",
    "desc_ja": "古宇利島の北端、ティーヌ浜の東側に位置する天然の穴場ビーチ。円筒状に穴の空いた巨大な奇岩「ポットホール（円筒状空洞群）」と遠浅のサンゴ礁が広がる。",
    "desc_en": "A tranquil natural beach on Kouri's northern coast famous for mysterious geological pot-hole limestone towers and vibrant shallow coral reefs teeming with reef fish.",
    "price": "見学自由",
    "price_ja": "見学自由",
    "price_en": "Free beach access",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.7136,
    "lng": 128.0317,
    "rain": False,
    "kids": True,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 観光客で賑わうハートロックと対照的にとても静かで、波打ち際すぐの浅瀬で熱帯魚が泳ぎ回るためシュノーケリングに最適です。",
    "tip_ja": "💡 観光客で賑わうハートロックと対照的にとても静かで、波打ち際すぐの浅瀬で熱帯魚が泳ぎ回るためシュノーケリングに最適です。",
    "tip_en": "Much quieter than adjacent Heart Rock. Colorful tropical damselfish and clownfish swim right up to the shoreline, making it an idyllic snorkeling paradise.",
    "categories": ["Scenery"]
  },
  {
    "id": "oki_p_60",
    "name": "羽地内海・嵐山展望台",
    "name_ja": "羽地内海・嵐山展望台",
    "name_en": "Arashiyama Observatory (Haneji Inland Sea)",
    "category": "Scenery & Nature",
    "rating": "★4.5",
    "desc": "名護市の北部に位置する穴場展望台。「沖縄の瀬戸内海」と呼ばれる波静かな羽地内海と、屋我地島や古宇利島、緑の島々が浮かぶ絶景を眼下に見渡せる。",
    "desc_ja": "名護市の北部に位置する穴場展望台。「沖縄の瀬戸内海」と呼ばれる波静かな羽地内海と、屋我地島や古宇利島、緑の島々が浮かぶ絶景を眼下に見渡せる。",
    "desc_en": "A tranquil elevated viewpoint in Nago overlooking the serene Haneji Inland Sea, often dubbed Okinawa's Seto Inland Sea for its sheltered waters and forested islets.",
    "price": "見学無料・駐車場無料",
    "price_ja": "見学無料・駐車場無料",
    "price_en": "Free observatory access",
    "image": "",
    "wikiImage": "",
    "hasWiki": False,
    "locationZone": "suburban",
    "lat": 26.6389,
    "lng": 127.9997,
    "rain": False,
    "kids": False,
    "shopping": False,
    "free": True,
    "top7": False,
    "hiddenGem": True,
    "is_night_spot": False,
    "tip": "💡 古宇利島へ向かうドライブの途中に立ち寄れる絶景スポット。パイナップル畑が広がるのどかな山道を抜けた先にあり、混雑知らずで大自然を満喫できます。",
    "tip_ja": "💡 古宇利島へ向かうドライブの途中に立ち寄れる絶景スポット。パイナップル畑が広がるのどかな山道を抜けた先にあり、混雑知らずで大自然を満喫できます。",
    "tip_en": "An effortless scenic detour en route to Kouri Island. Winding country lanes lined with pineapple fields lead up to this crowd-free panoramic vista.",
    "categories": ["Scenery"]
  }
]

combined = spots + new_batch
print(f"Total spots combined: {len(spots)} + {len(new_batch)} = {len(combined)} spots.")

with open('data/cities/okinawa.json', 'w', encoding='utf-8') as f:
    json.dump(combined, f, indent=2, ensure_ascii=False)
